org.gradle.jvmargs=-Xmx2048m -XX:MetaspaceSize=768m
android.nonTransitiveClass=true
android.useAndroidX=true
org.gradle.parallel=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kapt=false
org.jetbrains.toBytecode.impl.DomainObjectBaseBytecode=0
kotlin.toBytecode.impl.DomainObjectBaseBytecode=0
